[build-system]
requires = [
    "scikit-build-core>=0.10",
    "pybind11>=2.12"
]
build-backend = "scikit_build_core.build"

[project]
name = "mxslcxx"
version = "0.3.1"
description = "Python bindings for mxslc++"
readme = "README_PYPI.md"
requires-python = ">=3.9"
authors = [
    { name = "Jacob Thorn", email="jakethorn1.1@gmail.com" }
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.scripts]
mxslcxx = "mxslc.__main__:main"

[project.urls]
Homepage = "https://github.com/jakethorn/ShadingLanguageX"
Repository = "https://github.com/jakethorn/ShadingLanguageX"
Issues = "https://github.com/jakethorn/ShadingLanguageX/issues"

[tool.scikit-build]
minimum-version = "build-system.requires"
cmake.version = ">=3.28"
cmake.define = { BUILD_TESTING = "OFF" }
build-dir = "build/{wheel_tag}"

wheel.packages = ["python/mxslc"]

sdist.exclude = [
    ".venv",
    ".venv/**",
    ".build-venv",
    ".build-venv/**",
    ".test-venv",
    ".test-venv/**",
    "build",
    "build/**",
    "cmake-build-*",
    "cmake-build-*/**",
    "dist",
    "dist/**",
    ".git",
    ".git/**",
    ".github",
    ".github/**",
    ".idea",
    ".idea/**",
]

[tool.cibuildwheel]
build = "cp312-*"
skip = "*-musllinux_* *-win32"

test-requires = [
    "pytest",
]

test-command = "python -m pytest {project}/python/tests"
